[project]
name = "fitnessdashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.31.0",
    "gspread>=5.12.0",
    "oauth2client>=4.1.3",
    "polars>=0.19.0",
    "pytest>=8.3.4"
]
